server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate  # Проверяет соответствие схемы, не создаёт/не изменяет таблицы
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Диалект для PostgreSQL

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

# Настройки JWT
jwt:
  secret: mySuperSecretKeyForJWTGenerationPleaseChangeInProductionAndKeepItLongEnough
  expiration: 86400000  # 24 часа в миллисекундах